test: fix startup url

diff --git a/t/scenarios/auth_krb5/Makefile b/t/scenarios/auth_krb5/Makefile
--- a/t/scenarios/auth_krb5/Makefile
+++ b/t/scenarios/auth_krb5/Makefile
@@ -5,6 +5,6 @@ export THRUK_TEST_AUTH_KEY           = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
 
 wait_start:
 	for x in $$(seq $(STARTUPWAIT)); do \
-	   if [ $$(curl -ks https://127.0.0.3:60080/demo/thruk/cgi-bin/remote.cgi | grep -c OK) -gt 0 ]; then break; else sleep 1; fi; \
-	   if [ $$x -eq $(STARTUPWAIT) ]; then echo "ERROR: startup failed"; docker ps; curl -kv https://127.0.0.3:60080/demo/thruk/cgi-bin/remote.cgi; exit 1; fi; \
+	   if [ $$(curl -ks http://127.0.0.3:60080/demo/thruk/cgi-bin/remote.cgi | grep -c OK) -gt 0 ]; then break; else sleep 1; fi; \
+	   if [ $$x -eq $(STARTUPWAIT) ]; then echo "ERROR: startup failed"; docker ps; curl -kv http://127.0.0.3:60080/demo/thruk/cgi-bin/remote.cgi; exit 1; fi; \
 	done
