tests: be more verbose on container startup failures

diff --git a/t/scenarios/Makefile.common b/t/scenarios/Makefile.common
--- a/t/scenarios/Makefile.common
+++ b/t/scenarios/Makefile.common
@@ -9,10 +9,19 @@ wait_start:
 	$(THRUK) cache clean
 	for x in $$(seq $(STARTUPWAIT)); do \
 	   if [ $$($(THRUK) -l 2>&1 | grep -v ^Def | grep -v ^- | grep -v ERROR | grep OK | wc -l) -eq $(EXPECTED_BACKENDS) ]; then break; else sleep 1; fi; \
-	   if [ $$x -eq $(STARTUPWAIT) ]; then echo "ERROR: startup failed"; docker ps; $(THRUK) -l; exit 1; fi; \
+	   if [ $$x -eq $(STARTUPWAIT) ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	done
 	$(THRUK) -l
 	$(MAKE) extra_wait_start
+
+wait_start_failed:
+	-echo "ERROR: startup failed"
+	-test -e thruk.conf && $(THRUK) -l
+	-docker ps
+	-docker-compose logs --tail=20 --no-color -t | sort
+	$(MAKE) wait_start_failed_extra
+
+wait_start_failed_extra:
 
 test: wait_start
 	cd ../../.. && PERL_DL_NONLAZY=1 /usr/bin/env perl "-MExtUtils::Command::MM" "-e" "test_harness(0)" $(shell pwd)/t/*.t
