fix test scenario
exit on provision errors

diff --git a/t/scenarios/_common/Makefile.common b/t/scenarios/_common/Makefile.common
--- a/t/scenarios/_common/Makefile.common
+++ b/t/scenarios/_common/Makefile.common
@@ -85,6 +85,7 @@ prepare:
 	@docker-compose logs -f | while read LOGLINE; do \
 		echo "$${LOGLINE}"; \
 		[[ "$${LOGLINE}" == *"Starting Apache web server"* ]] && pkill -P $$$$ docker-compose && exit 0; \
+		[[ "$${LOGLINE}" == *"ERROR"* ]] && pkill -P $$$$ docker-compose && exit 1; \
 	done
 	@echo "### $@: $$(date "+%FT%T.%N")"
 	$(MAKE) extra_prepare
