tests: check for ansible errors on wait_start

diff --git a/t/scenarios/_common/Makefile.common b/t/scenarios/_common/Makefile.common
--- a/t/scenarios/_common/Makefile.common
+++ b/t/scenarios/_common/Makefile.common
@@ -18,6 +18,7 @@ wait_start:
 	$(THRUK) cache clean
 	for x in $$(seq $(STARTUPWAIT)); do \
 	   if [ $$(docker-compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
+	   if [ $$(docker-compose logs | grep "| ERROR" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	   if [ $$($(THRUK) -l 2>&1 | grep -v ^Def | grep -v ^- | grep -v ERROR | grep OK | wc -l) -eq $(EXPECTED_BACKENDS) ]; then break; else sleep 1; fi; \
 	   if [ $$x -eq $(STARTUPWAIT) ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	done
