tests: migrate docker-compose to builtin docker compose

diff --git a/t/scenarios/_common/Makefile.common b/t/scenarios/_common/Makefile.common
--- a/t/scenarios/_common/Makefile.common
+++ b/t/scenarios/_common/Makefile.common
@@ -18,8 +18,8 @@ export COMPOSE_HTTP_TIMEOUT=180
 wait_start:
 	$(THRUK) cache clean
 	for x in $$(seq $(STARTUPWAIT)); do \
-	   if [ $$(docker-compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
-	   if [ $$(docker-compose logs | grep "| ERROR" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
+	   if [ $$(docker compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
+	   if [ $$(docker compose logs | grep "| ERROR" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	   if [ $$($(THRUK) -l 2>&1 | grep -v ^Def | grep -v ^- | grep -v ERROR | grep OK | wc -l) -eq $(EXPECTED_BACKENDS) ]; then break; else sleep 1; fi; \
 	   if [ $$x -eq $(STARTUPWAIT) ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	done
@@ -32,15 +32,15 @@ wait_start_failed: wait_start_short_errors non_interactive_only
 wait_start_short_errors:
 	@echo "### $@: $$(date "+%FT%T.%N")"
 	-echo "ERROR: startup failed"
-	-docker-compose logs | grep "| ERROR"
-	-docker-compose logs | grep "failed=" | grep -v "failed=0"
+	-docker compose logs | grep "| ERROR"
+	-docker compose logs | grep "failed=" | grep -v "failed=0"
 
 wait_start_info:
 	@echo "### $@: $$(date "+%FT%T.%N")"
 	-echo "ERROR: startup failed"
 	-test -e thruk.conf && $(THRUK) -vvv -l
 	-docker ps
-	-docker-compose logs --tail=30 $(DOCKER_COMPOSE_LOGS) -t | sort
+	-docker compose logs --tail=30 $(DOCKER_COMPOSE_LOGS) -t | sort
 	$(MAKE) wait_start_failed_extra
 
 wait_start_failed_extra:
@@ -80,10 +80,10 @@ failed_test_info:
 	@echo "### $@: $$(date "+%FT%T.%N")"
 	-echo "ERROR: test failed"
 	-docker ps
-	-docker-compose logs --tail=30 $(DOCKER_COMPOSE_LOGS) -t | sort
-	for svc in $$(docker-compose config --services | sort); do \
+	-docker compose logs --tail=30 $(DOCKER_COMPOSE_LOGS) -t | sort
+	for svc in $$(docker compose config --services | sort); do \
 		index=0; \
-		for container in $$(docker-compose ps -q $$svc); do \
+		for container in $$(docker compose ps -q $$svc); do \
 			index=$$(( index + 1 )); \
 			echo "*** $${svc}_$${index}"; \
 			if docker exec -t --user root $$container test -d /opt/omd/sites/demo; then \
@@ -129,15 +129,15 @@ preprepare:
 prepare: base_images
 	$(MAKE) preprepare
 	@echo "### $@: $$(date "+%FT%T.%N")"
-	docker-compose build
-	docker-compose up --remove-orphans -d
+	docker compose build
+	docker compose up --remove-orphans -d
 	docker ps
-	@docker-compose logs -t $(DOCKER_COMPOSE_LOGS) -f | while read LOGLINE; do \
+	@docker compose logs -t $(DOCKER_COMPOSE_LOGS) -f | while read LOGLINE; do \
 		echo "$${LOGLINE}"; \
-		[[ "$${LOGLINE}" == *"Starting Apache web server"* ]] && pkill -P $$$$ docker-compose && exit 0; \
-		[[ "$${LOGLINE}" == *"ci container ready"* ]]         && pkill -P $$$$ docker-compose -9 && exit 0; \
-		[[ "$${LOGLINE}" == *"ERROR"* ]]                      && pkill -P $$$$ docker-compose && exit 1; \
-		[[ "$${LOGLINE}" == *"exited with code"* ]]           && pkill -P $$$$ docker-compose && exit 1; \
+		[[ "$${LOGLINE}" == *"Starting Apache web server"* ]] && pkill -P $$$$ "docker"    && exit 0; \
+		[[ "$${LOGLINE}" == *"ci container ready"* ]]         && pkill -P $$$$ "docker" -9 && exit 0; \
+		[[ "$${LOGLINE}" == *"ERROR"* ]]                      && pkill -P $$$$ "docker"    && exit 1; \
+		[[ "$${LOGLINE}" == *"exited with code"* ]]           && pkill -P $$$$ "docker"    && exit 1; \
 	done
 	@echo "### $@: $$(date "+%FT%T.%N")"
 	$(MAKE) extra_prepare
@@ -145,10 +145,10 @@ prepare: base_images
 
 clean:
 	@echo "### $@: $$(date "+%FT%T.%N")"
-	docker-compose down -v --rmi all
-	docker-compose kill -s INT
-	docker-compose kill
-	docker-compose rm -f
+	docker compose down -v --rmi all
+	docker compose kill -s INT
+	docker compose kill
+	docker compose rm -f
 	-test -e thruk.conf && $(THRUK) cache clean all
 	@echo "### $@: $$(date "+%FT%T.%N")"
 	$(MAKE) extra_clean
@@ -163,7 +163,7 @@ base_images:
 
 update:
 	@echo "### $@: $$(date "+%FT%T.%N")"
-	docker-compose pull
+	docker compose pull
 	for IMG in $$(grep FROM */Dockerfile | awk '{ print $$2 }' | grep -v local/ | sort -u); do docker pull $$IMG; done
 	if $$(grep FROM */Dockerfile | awk '{ print $$2 }' | grep local/ >/dev/null); then make -C ../_common update; fi
 	@echo "### $@: $$(date "+%FT%T.%N")"
diff --git a/t/scenarios/agents-plugin/Makefile b/t/scenarios/agents-plugin/Makefile
--- a/t/scenarios/agents-plugin/Makefile
+++ b/t/scenarios/agents-plugin/Makefile
@@ -5,7 +5,7 @@ export PLACK_TEST_EXTERNALSERVER_URI = http://127.0.0.3:60080/demo/
 
 wait_start:
 	for x in $$(seq $(STARTUPWAIT)); do \
-	   if [ $$(docker-compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
+	   if [ $$(docker compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	   if [ $$(curl -s http://127.0.0.3:60080/demo/thruk/cgi-bin/login.cgi | grep -c loginuser) -gt 0 ]; then break; else sleep 1; fi; \
 	   if [ $$x -eq $(STARTUPWAIT) ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	done
@@ -17,12 +17,12 @@ wait_start_failed_extra:
 	-curl -kv http://127.0.0.3:60080/demo/thruk/cgi-bin/login.cgi
 
 extra_prepare:
-	@printf "%s:omd version: %s\n" "$(shell grep FROM omd/Dockerfile)" $$(docker-compose exec $(DOCKER_COMPOSE_TTY) --user root omd sudo -iu demo omd version -b)
+	@printf "%s:omd version: %s\n" "$(shell grep FROM omd/Dockerfile)" $$(docker compose exec $(DOCKER_COMPOSE_TTY) --user root omd sudo -iu demo omd version -b)
 
 extra_test:
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root omd sudo -iu demo /usr/local/bin/local_test.sh 0 /test/t/local/omd/*.t
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root livestatus-backend sudo -iu demo /usr/local/bin/local_test.sh 0 /test/t/local/livestatus-backend/*.t
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root omd sudo -iu demo /usr/local/bin/local_test.sh 0 /test/t/local/omd/*.t
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root livestatus-backend sudo -iu demo /usr/local/bin/local_test.sh 0 /test/t/local/livestatus-backend/*.t
 
 extra_test_verbose:
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root omd sudo -iu demo /usr/local/bin/local_test.sh 1 /test/t/local/omd/*.t
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root livestatus-backend sudo -iu demo /usr/local/bin/local_test.sh 1 /test/t/local/livestatus-backend/*.t
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root omd sudo -iu demo /usr/local/bin/local_test.sh 1 /test/t/local/omd/*.t
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root livestatus-backend sudo -iu demo /usr/local/bin/local_test.sh 1 /test/t/local/livestatus-backend/*.t
diff --git a/t/scenarios/auth_krb5/Makefile b/t/scenarios/auth_krb5/Makefile
--- a/t/scenarios/auth_krb5/Makefile
+++ b/t/scenarios/auth_krb5/Makefile
@@ -5,7 +5,7 @@ export THRUK_TEST_AUTH_KEY           = ff8cde7bc92c261a260a180ef4d35c456853b70d9
 
 wait_start:
 	for x in $$(seq $(STARTUPWAIT)); do \
-	   if [ $$(docker-compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
+	   if [ $$(docker compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	   if [ $$(curl -ks http://127.0.0.3:60080/demo/thruk/cgi-bin/remote.cgi | grep -c OK) -gt 0 ]; then break; else sleep 1; fi; \
 	   if [ $$x -eq $(STARTUPWAIT) ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	done
@@ -14,10 +14,10 @@ wait_start_failed_extra:
 	-curl -kv http://127.0.0.3:60080/demo/thruk/cgi-bin/remote.cgi
 
 extra_test:
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root omd sudo -iu demo /usr/local/bin/local_test.sh 0
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root omd sudo -iu demo /usr/local/bin/local_test.sh 0
 
 extra_test_verbose:
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root omd sudo -iu demo /usr/local/bin/local_test.sh 1
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root omd sudo -iu demo /usr/local/bin/local_test.sh 1
 
 webvnc:
 	@python3 -m webbrowser http://127.0.0.3:6901/?password=vncpassword
diff --git a/t/scenarios/auth_oauth/Makefile b/t/scenarios/auth_oauth/Makefile
--- a/t/scenarios/auth_oauth/Makefile
+++ b/t/scenarios/auth_oauth/Makefile
@@ -2,7 +2,7 @@ include ../_common/Makefile.common
 
 wait_start:
 	for x in $$(seq $(STARTUPWAIT)); do \
-	   if [ $$(docker-compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
+	   if [ $$(docker compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	   if [ $$(curl -ks http://127.0.0.3:60080/demo/thruk/cgi-bin/remote.cgi | grep -c OK) -gt 0 ]; then break; else sleep 1; fi; \
 	   if [ $$x -eq $(STARTUPWAIT) ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	done
diff --git a/t/scenarios/auth_ssl_client_cert/Makefile b/t/scenarios/auth_ssl_client_cert/Makefile
--- a/t/scenarios/auth_ssl_client_cert/Makefile
+++ b/t/scenarios/auth_ssl_client_cert/Makefile
@@ -4,7 +4,7 @@ export PLACK_TEST_EXTERNALSERVER_URI = https://127.0.0.3:60443/demo/
 
 wait_start:
 	for x in $$(seq $(STARTUPWAIT)); do \
-	   if [ $$(docker-compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
+	   if [ $$(docker compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	   if [ $$(curl -ks $(PLACK_TEST_EXTERNALSERVER_URI)thruk/cgi-bin/login.cgi | grep -c loginuser) -gt 0 ]; then break; else sleep 1; fi; \
 	   if [ $$x -eq $(STARTUPWAIT) ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	done
@@ -16,7 +16,7 @@ server:
 	@echo -e "\n\n*** no server implemented, access via https://$(shell hostname):60443/demo/\n"
 
 extra_test:
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root site sudo -iu demo /usr/local/bin/local_test.sh 0
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root site sudo -iu demo /usr/local/bin/local_test.sh 0
 
 extra_test_verbose:
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root site sudo -iu demo /usr/local/bin/local_test.sh 1
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root site sudo -iu demo /usr/local/bin/local_test.sh 1
diff --git a/t/scenarios/backend_http_readonly/Makefile b/t/scenarios/backend_http_readonly/Makefile
--- a/t/scenarios/backend_http_readonly/Makefile
+++ b/t/scenarios/backend_http_readonly/Makefile
@@ -5,7 +5,7 @@ export PLACK_TEST_EXTERNALSERVER_URI = http://127.0.0.3:60080/demo/
 
 wait_start:
 	for x in $$(seq $(STARTUPWAIT)); do \
-	   if [ $$(docker-compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
+	   if [ $$(docker compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	   if [ $$(curl -s http://127.0.0.3:60080/demo/thruk/cgi-bin/login.cgi | grep -c loginuser) -gt 0 ]; then break; else sleep 1; fi; \
 	   if [ $$x -eq $(STARTUPWAIT) ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	done
@@ -14,7 +14,7 @@ wait_start_failed_extra:
 	-curl -kv http://127.0.0.3:60080/demo/thruk/cgi-bin/login.cgi
 
 extra_test:
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root omd sudo -iu demo /usr/local/bin/local_test.sh 0
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root omd sudo -iu demo /usr/local/bin/local_test.sh 0
 
 extra_test_verbose:
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root omd sudo -iu demo /usr/local/bin/local_test.sh 1
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root omd sudo -iu demo /usr/local/bin/local_test.sh 1
diff --git a/t/scenarios/citest/Makefile b/t/scenarios/citest/Makefile
--- a/t/scenarios/citest/Makefile
+++ b/t/scenarios/citest/Makefile
@@ -12,9 +12,9 @@ extra_prepare:
 
 wait_start:
 	for x in $$(seq $(STARTUPWAIT)); do \
-	   if [ $$(docker-compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
-	   if [ $$(docker-compose logs | grep "| ERROR" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
-	   if [ $$(docker-compose logs | grep "ci container ready" | wc -l) -eq 1 ]; then break; else sleep 1; fi; \
+	   if [ $$(docker compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
+	   if [ $$(docker compose logs | grep "| ERROR" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
+	   if [ $$(docker compose logs | grep "ci container ready" | wc -l) -eq 1 ]; then break; else sleep 1; fi; \
 	   if [ $$x -eq $(STARTUPWAIT) ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	done
 	docker ps
diff --git a/t/scenarios/cluster_fixed_e2e/Makefile b/t/scenarios/cluster_fixed_e2e/Makefile
--- a/t/scenarios/cluster_fixed_e2e/Makefile
+++ b/t/scenarios/cluster_fixed_e2e/Makefile
@@ -5,16 +5,16 @@ export PLACK_TEST_EXTERNALSERVER_URI = http://127.0.0.3:60080/demo/
 
 wait_start:
 	for x in $$(seq $(STARTUPWAIT)); do \
-	   if [ $$(docker-compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
-	   docker-compose exec $(DOCKER_COMPOSE_TTY) --user root thruk1 sudo -iu demo thruk cluster ping >/dev/null 2>&1; \
-	   if [ $$(docker-compose exec $(DOCKER_COMPOSE_TTY) --user root thruk1 sudo -iu demo thruk cluster status | grep -c OK) -eq 3 ]; then break; else sleep 1; fi; \
+	   if [ $$(docker compose logs | grep "failed=" | grep -v "failed=0" | wc -l) -gt 0 ]; then $(MAKE) wait_start_failed; exit 1; fi; \
+	   docker compose exec $(DOCKER_COMPOSE_TTY) --user root thruk1 sudo -iu demo thruk cluster ping >/dev/null 2>&1; \
+	   if [ $$(docker compose exec $(DOCKER_COMPOSE_TTY) --user root thruk1 sudo -iu demo thruk cluster status | grep -c OK) -eq 3 ]; then break; else sleep 1; fi; \
 	   if [ $$x -eq $(STARTUPWAIT) ]; then $(MAKE) wait_start_failed; exit 1; fi; \
 	done
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root thruk1 sudo -iu demo thruk cluster ping
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root thruk1 sudo -iu demo thruk cluster status
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root thruk1 sudo -iu demo thruk r -m POST /thruk/cluster/heartbeat
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root thruk2 sudo -iu demo thruk r -m POST /thruk/cluster/heartbeat
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root thruk3 sudo -iu demo thruk r -m POST /thruk/cluster/heartbeat
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root thruk1 sudo -iu demo thruk cluster ping
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root thruk1 sudo -iu demo thruk cluster status
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root thruk1 sudo -iu demo thruk r -m POST /thruk/cluster/heartbeat
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root thruk2 sudo -iu demo thruk r -m POST /thruk/cluster/heartbeat
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root thruk3 sudo -iu demo thruk r -m POST /thruk/cluster/heartbeat
 
 wait_start_failed_extra:
 	-curl -kv http://127.0.0.3:60080/demo/thruk/cgi-bin/login.cgi
@@ -26,7 +26,7 @@ extra_clean:
 	-docker volume rm cluster_fixed_e2e_shared_var
 
 extra_test:
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root thruk1 sudo -iu demo /usr/local/bin/local_test.sh 0
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root thruk1 sudo -iu demo /usr/local/bin/local_test.sh 0
 
 extra_test_verbose:
-	docker-compose exec $(DOCKER_COMPOSE_TTY) --user root thruk1 sudo -iu demo /usr/local/bin/local_test.sh 1
+	docker compose exec $(DOCKER_COMPOSE_TTY) --user root thruk1 sudo -iu demo /usr/local/bin/local_test.sh 1
