tests: try to avoid port bind issues
Signed-off-by: Sven Nierlein <sven@nierlein.de>

diff --git a/t/scenarios/cluster_e2e/Makefile b/t/scenarios/cluster_e2e/Makefile
--- a/t/scenarios/cluster_e2e/Makefile
+++ b/t/scenarios/cluster_e2e/Makefile
@@ -1,12 +1,12 @@
 include ../Makefile.common
 
 export THRUK_TEST_AUTH               = omdadmin:omd
-export PLACK_TEST_EXTERNALSERVER_URI = http://localhost:60080/demo/
+export PLACK_TEST_EXTERNALSERVER_URI = http://127.0.0.3:60080/demo/
 
 wait_start:
 	for x in $$(seq $(STARTUPWAIT)); do \
-	   if [ $$(curl -s http://localhost:60080/demo/thruk/cgi-bin/login.cgi | grep -c Login) -gt 0 ]; then break; else sleep 1; fi; \
-	   if [ $$x -eq $(STARTUPWAIT) ]; then echo "ERROR: startup failed"; docker ps; curl http://localhost:60080/demo/thruk/cgi-bin/login.cgi; exit 1; fi; \
+	   if [ $$(curl -s http://127.0.0.3:60080/demo/thruk/cgi-bin/login.cgi | grep -c Login) -gt 0 ]; then break; else sleep 1; fi; \
+	   if [ $$x -eq $(STARTUPWAIT) ]; then echo "ERROR: startup failed"; docker ps; curl http://127.0.0.3:60080/demo/thruk/cgi-bin/login.cgi; exit 1; fi; \
 	done
 
 extra_clean:
diff --git a/t/scenarios/sakuli_e2e/Makefile b/t/scenarios/sakuli_e2e/Makefile
--- a/t/scenarios/sakuli_e2e/Makefile
+++ b/t/scenarios/sakuli_e2e/Makefile
@@ -4,9 +4,9 @@ wait_start:
 	-mkdir -p _run
 	-chmod 777 _run
 	for x in $$(seq $(STARTUPWAIT)); do \
-	   curl http://localhost:60080/demo/thruk/cgi-bin/login.cgi >/dev/null 2>&1; \
+	   curl http://127.0.0.3:60080/demo/thruk/cgi-bin/login.cgi >/dev/null 2>&1; \
 	   if [ $$? -eq 0 ]; then break; else sleep 1; fi; \
-	   if [ $$x -eq $(STARTUPWAIT) ]; then echo "ERROR: startup failed"; docker ps; curl http://localhost:60080/demo/thruk/cgi-bin/login.cgi; exit 1; fi; \
+	   if [ $$x -eq $(STARTUPWAIT) ]; then echo "ERROR: startup failed"; docker ps; curl http://127.0.0.3:60080/demo/thruk/cgi-bin/login.cgi; exit 1; fi; \
 	done
 
 test: test_chrome test_firefox
